### PR TITLE
Analyze the package with RcppDeepState

### PR DESCRIPTION
**Pull request by FabrizioSandri**
### RcppDeepState Analysis
This package contains problems, according to RcppDeepState. The report was generated by [RcppDeepState-action](https://github.com/FabrizioSandri/RcppDeepState-action) in this repository's fork and is accessible [here]( https://github.com/RcppDeepState/Quartet/pull/1 ).

### CODE REVIEW

**Comment by FabrizioSandri** [comment]
## [RcppDeepState](https://github.com/FabrizioSandri/RcppDeepState) Report
|function name|message|file line|address trace|R code|
|-|-|-|-|-|
|all_quartets|8 bytes in 1 blocks are definitely lost in loss record 7 of 1,293|[AllQuartets.cpp:33](https://github.com/RcppDeepState/Quartet/blob/20f0c8cfedcbf4821c7dceca16d10f3204ff5c1a/src/AllQuartets.cpp#L33)|No Address Trace found|<details><summary>Test code</summary><pre>testlist <- list(nTips = c(-1034462886L, 130012951L, -1915885210L, -1538685084L, -1705104631L, -1023490640L, -1272709731L, -1200673158L, -964176434L, 1185736148L, 2060335646L, 398558129L, 548322018L, -1400925600L, -1567621542L, -13838907L, -1280666631L, 1450757584L, 1174925149L, -915271959L, 550030284L, 1214066154L, -332708373L, 1461367050L, -1002175718L, -1110316285L, -656776799L, 1282378348L, 945109120L, -1301976417L, -1867543833L, -918818419L, -2131384259L, -963428194L, 1839284409L, 298460489L, 543017426L, -1020038829L, -470008916L, 925645495L, 568521959L, 1966442210L, -691627033L))<br/>result <- do.call(Quartet:::all_quartets, testlist)</pre></details>|
|tqdist_OneToManyQuartetAgreementChar|62 bytes in 1 blocks are possibly lost in loss record 24 of 1,307|[NewickParser.cpp:77](https://github.com/RcppDeepState/Quartet/blob/20f0c8cfedcbf4821c7dceca16d10f3204ff5c1a/src/NewickParser.cpp#L77)|No Address Trace found|<details><summary>Test code</summary><pre>testlist <- list(tree = c(NA, "uxrvwcycbzpjndhsrhbx", NA, "bxancqcmncsbqunzxvdy", "xznvtbir", NA, "", "whuzntssyhhjwh", "qrykbefxwnqcmfulbmzq", "lbnu", "gwsmtlogwrf", "", "qxpibgflblxeppmqiqum", "kljvsbzllaywqlwquets", "evkiazrttskmbfrqomis", NA, "osiwjhxdvlbuvgpdv", "rihbxigzoxjodgkznddm", NA, "cdtcwzfhoqvvmwdktsjv", "seyfnbdbbqsdsyqmugjk", NA, "isgbkhaerzraurxzztfn", "zanoxtjidozbchwqhvaz", "bugwxhnhowjqanwvwqvo", NA, NA, "oiedwjpdskyhyspbymdu", NA, "llwsiiacud", "hxehpf", NA, NA, "efjgmdrwlvpztsmxht", "mpjyuzstmucaaithqjuv", "thqujeonwbwnfyawlkma", NA, "ggmaszxzqshphbboctpv", "usdevabdwbic", "eaerhepugn", NA, "ibbkjoecdahbmxgckxj"), trees = c("tafittgehdoumeohnyhr", "knrcfmytenlyfsfgukzu", "whrxkhjabyplglpszqcv", NA, NA))<br/>result <- do.call(Quartet:::tqdist_OneToManyQuartetAgreementChar, testlist)</pre></details>|
|tqdist_QuartetAgreementChar|62 bytes in 1 blocks are possibly lost in loss record 24 of 1,307|[NewickParser.cpp:77](https://github.com/RcppDeepState/Quartet/blob/20f0c8cfedcbf4821c7dceca16d10f3204ff5c1a/src/NewickParser.cpp#L77)|No Address Trace found|<details><summary>Test code</summary><pre>testlist <- list(string1 = c(NA, "uxrvwcycbzpjndhsrhbx", NA, "bxancqcmncsbqunzxvdy", "xznvtbir", NA, "", "whuzntssyhhjwh", "qrykbefxwnqcmfulbmzq", "lbnu", "gwsmtlogwrf", "", "qxpibgflblxeppmqiqum", "kljvsbzllaywqlwquets", "evkiazrttskmbfrqomis", NA, "osiwjhxdvlbuvgpdv", "rihbxigzoxjodgkznddm", NA, "cdtcwzfhoqvvmwdktsjv", "seyfnbdbbqsdsyqmugjk", NA, "isgbkhaerzraurxzztfn", "zanoxtjidozbchwqhvaz", "bugwxhnhowjqanwvwqvo", NA, NA, "oiedwjpdskyhyspbymdu", NA, "llwsiiacud", "hxehpf", NA, NA, "efjgmdrwlvpztsmxht", "mpjyuzstmucaaithqjuv", "thqujeonwbwnfyawlkma", NA, "ggmaszxzqshphbboctpv", "usdevabdwbic", "eaerhepugn", NA, "ibbkjoecdahbmxgckxj"), string2 = c("tafittgehdoumeohnyhr", "knrcfmytenlyfsfgukzu", "whrxkhjabyplglpszqcv", NA, NA))<br/>result <- do.call(Quartet:::tqdist_QuartetAgreementChar, testlist)</pre></details>|
### Analyzed functions summary
|function name|tested inputs|inputs with issues|
|-|-|-|
|all_quartets|3|3|
|tqdist_AllPairsQuartetAgreement|3|0|
|tqdist_AllPairsQuartetAgreementChar|3|0|
|tqdist_AllPairsQuartetDistance|3|0|
|tqdist_AllPairsQuartetDistanceChar|3|0|
|tqdist_AllPairsTripletDistance|3|0|
|tqdist_OneToManyQuartetAgreement|3|0|
|tqdist_OneToManyQuartetAgreementChar|3|2|
|tqdist_PairsQuartetDistance|3|0|
|tqdist_PairsTripletDistance|3|0|
|tqdist_QuartetAgreement|3|0|
|tqdist_QuartetAgreementChar|3|2|
|tqdist_QuartetDistance|3|0|
|tqdist_TripletDistance|3|0|
|which_index|3|0|
### Report details
* Report generated by: 20f0c8c
* Inputs generator seed: 1661799024

**Comment by ms609** [comment]
Thanks for this – problems now patched (I think – we'll see whether the test passes!)

Is setting up the checks for my other repos (https://github.com/ms609/TreeTools, https://github.com/ms609/TreeSearch, https://github.com/ms609/TreeDist, https://github.com/ms609/Rogue) as easy as copying and pasting the script you've provided, or would you recommend tweaks / are other steps required?

**Comment by FabrizioSandri** [comment]
@ms609 I appreciate you include this new action in your repository.

If you are familiar with workflows, I recommend manually copying and pasting the [RcppDeepState.yml](https://github.com/ms609/Quartet/blob/master/.github/workflows/RcppDeepState.yml) workflow file into your repository and adjusting the parameters according to the instructions provided in the action's repository's README file. 

One thing to keep in mind is the `location` option supplied to the action: relative path to the repository's root where the package to be evaluated is placed; if your package is not stored in the repository's root, please specify the location relative to root.

**Comment by ms609** [comment]
Thanks. At  

I see the message
```
We can't test the function - all_tbr - due to the following datatypes falling out of the allowed ones: IntegerMatrix
```

which seems to cause the [entire run](https://github.com/ms609/TreeSearch/actions/runs/2956693949) to fail – is this the anticipated behaviour?

**Comment by FabrizioSandri** [comment]
RcppDeepState currently supports the analysis of the following datatypes: 

* `Rcpp::NumericVector`
* `Rcpp::NumericMatrix`
* `Rcpp::CharacterVector`
* `Rcpp::IntegerVector`
* `arma::mat`
* `std::double`
* `std::string`
* `std::int`

In this scenario, the package you are trying to analyze includes all functions that use at least one unsupported datatype: `IntegerMatrix`. I have in plan to add support for other datatypes to RcppDeepState. 

As a workaround you can:
* provide a manually built test harness for these functions; here you can find a detailed guide [Provide a custom test harness to RcppDeepState GitHub Action](https://fabriziosandri.github.io/gsoc-2022-blog/rcppdeepstate/github%20action/2022/08/11/action-custom-harness.html).
* add support for this datatype to RcppDeepState, however, follow this guide [Add a new datatype to RcppDeepState](https://github.com/FabrizioSandri/RcppDeepState/wiki/Add-a-new-datatype-to-RcppDeepState)

**Comment by ms609** [comment]
Thanks; I've submitted a PR for the IntegerMatrix type.  As writing a custom test harness for each function would entail quite a bit of technical expertise, I wonder whether you might consider allowing the user (or documenting?) an option to simply skip all functions that aren't supported by the current RcppDeepState build?

Thanks for the useful package - hoepfully this will end up sparing my users a few crashes down the line!

**Comment by FabrizioSandri** [comment]
You are right, writing a custom test harness for each function it's a difficult task. Thank you for adding support for `IntegerMatrix` to RcppDeepState. You may now re-run this task to see if the functions with the argument `IntegerMatrix` are analyzed. 

> I wonder whether you might consider allowing the user (or documenting?) an option to simply skip all functions that aren't supported by the current RcppDeepState build?

Regarding this, RcppDeepState currently skips all functions that aren't supported, reporting a warning message. However, if the package only includes functions with unsupported datatypes, RcppDeepState will fail and display an error message. Instead of failing, I feel the acton should report that no function was analyzed without returning an error. I will fix this

**Comment by FabrizioSandri** [comment]
I still notice a linking problem in the [latest execution log](https://github.com/ms609/TreeSearch/runs/8108506879?check_suite_focus=true): 
```c++
 /github/workspace/src/rearrange.cpp:3:10: fatal error: 'TreeTools/renumber_tree.h' file not found
#include <TreeTools/renumber_tree.h> /* for preorder_edges_and_nodes */
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This has something to do with https://github.com/FabrizioSandri/RcppDeepState-action/issues/19. I'll update you when this problem is resolved; I'm working on it.

**Pull request merged**
